site_name: Confab Docs

nav:
  - Home: index.md
  - Overview:
    - overview/index.md
  - Quick Start Guide:
    - quick-start/index.md
  - Admin Guide:
    - admin-guide/index.md
    - Content Risks: admin-guide/content-risks/index.md
    - Abuse Mitigation: admin-guide/abuse-mitigation/index.md
    - Backups: admin-guide/backup/index.md
  - Core Functionality:
    - core-functionality/index.md
    - Comments: core-functionality/comments/index.md
    - Users: core-functionality/users/index.md
    - Comment Locations: core-functionality/location/index.md
    - Admin Panel: core-functionality/admin-panel/index.md
    - Automatic Moderation: core-functionality/auto-moderation/index.md
    - Manual Moderation: core-functionality/manual-moderation/index.md
    - Emails: core-functionality/emails/index.md
    - Edit History: core-functionality/edit-history/index.md
  - Backend Config Reference:
    - config/index.md
  - Development:
    - development/index.md
    - Database Schema Changes: development/database-schema-changes/index.md
  - About:
    - Design Philosophy: about/design.md
    - Future Roadmap: about/roadmap.md

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: custom
      accent: cyan
      toggle:
        icon: material/brightness-5
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      accent: blue
      toggle:
        icon: material/brightness-3
        name: Switch to system preference
  features:
    - announce.dismiss
    - content.action.edit
    - content.code.annotate
    - content.code.copy
    - content.tooltips
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
  icon:
    repo: fontawesome/brands/github
  logo: ../assets/docs.svg
  favicon: ../assets/docs.svg


edit_uri: https://github.com/nextguyover/Confab-Docs/blob/main/docs/

markdown_extensions:
  - attr_list
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - attr_list
  - md_in_html
  - abbr
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - toc:
      permalink: ⚓︎
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

plugins:
  - search
  - awesome-pages
  - markdownextradata: {}
  # - minify:
      # minify_html: true

repo_name: nextguyover/Confab
repo_url: https://github.com/nextguyover/Confab

# Additional configuration
extra:
  variables:
    CONFAB_GITHUB_LOCATION: nextguyover/Confab
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/thumb-up-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/thumb-down-outline
          name: This page could be improved
          data: 0
          note: >-
            Thanks for your feedback! Feel free to suggest edits for this page
            or create a new issue on the Confab Github Repo.    

extra_css:
  - stylesheets/extra.css